apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  annotations:
    kubernetes.io/change-couse: "Update nginx 1.17.3"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
      env: gorilla
  revisionHistoryLimit: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      name: nginx
      labels:
        app: web
        env: gorilla
    spec:
      containers:
      - name: nginx
        image: nginx:1.17.3-alpine